<?php

namespace Database\Seeders\Tools\CFIT;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tool;
use App\Models\Question;
use App\Models\Section;

class CfitQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cfit = Tool::firstWhere('name', 'CFIT');

        $questions = [
            // Contoh Subtes 1
            [
                'section_id' => $cfit->sections[0]->id,
                'order' => 1,
                'text' => '<p>Pada masing-masing soal terdapat 3 gambar dan 1 kotak kosong pada bagian terakhir. Satu kotak kosong tersebut merupakan lanjutan dari gambar-gambar sebelumnya.</p>
                <p>Tugas Anda adalah memilih gambar yang tepat dari pilihan jawaban yang tersedia pada masing-masing soal untuk mengisi kelanjutan dari gambar tersebut.</p>',
                'type' => 'instruction',
            ],
            [
                'section_id' => $cfit->sections[0]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/1/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[0]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/2/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[0]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-1/3/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],

            // Subtes 1
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 1,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/1/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/2/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/3/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/4/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 5,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/5/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 6,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/6/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 7,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/7/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 8,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/8/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 9,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/9/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'F'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 10,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/10/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 11,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/11/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 12,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/12/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[1]->id,
                'order' => 13,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-1/13/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],

            // Contoh Subtes 2
            [
                'section_id' => $cfit->sections[2]->id,
                'order' => 1,
                'text' => '<p>Pada masing-masing soal Anda akan menemui 5 pilihan gambar. Pada tiap soal tersebut terdapat 3 kotak yang mempunyai bentuk yang sama, tetapi ada juga 2 kotak yang mempunyai gambar berbeda dari 3 kotak lainnya.</p>
                <p>Tugas Anda adalah mencari pada tiap soal 2 kotak yang gambarnya berbeda dengan gambar-gambar lainnya.</p>',
                'type' => 'instruction',
            ],
            [
                'section_id' => $cfit->sections[2]->id,
                'order' => 2,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/1/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[2]->id,
                'order' => 3,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-2/2/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 0,
                    'C' => 1,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],

            // Subtes 2
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 1,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/1/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 2,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/2/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 0,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 3,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/3/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 0,
                    'C' => 0,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 4,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/4/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/4/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/4/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/4/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/4/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 0,
                    'C' => 1,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 5,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/5/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/5/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/5/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/5/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/5/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 6,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/6/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/6/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/6/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/6/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/6/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 0,
                    'C' => 0,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 7,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/7/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/7/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/7/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/7/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/7/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 8,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/8/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/8/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/8/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/8/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/8/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 9,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/9/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/9/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/9/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/9/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/9/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 0,
                    'C' => 0,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 10,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/10/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/10/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/10/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/10/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/10/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 0,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 11,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/11/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/11/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/11/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/11/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/11/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 0,
                    'C' => 0,
                    'D' => 0,
                    'E' => 1,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 12,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/12/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/12/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/12/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/12/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/12/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 0,
                    'C' => 1,
                    'D' => 1,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 13,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/13/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/13/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/13/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/13/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/13/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 0,
                    'B' => 1,
                    'C' => 1,
                    'D' => 0,
                    'E' => 0,
                ]],
            ],
            [
                'section_id' => $cfit->sections[3]->id,
                'order' => 14,
                'type' => 'image_multiple_select',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/14/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/14/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/14/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/14/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-2/14/E.webp'],
                ],
                'scoring' => ['scores' => [
                    'A' => 1,
                    'B' => 1,
                    'C' => 0,
                    'D' => 0,
                    'E' => 0,
                ]],
            ],

            // Contoh Subtes 3
            [
                'section_id' => $cfit->sections[4]->id,
                'order' => 1,
                'text' => '<p>Pada masing-masing soal Anda akan menemui 4 kotak kecil yang berada di dalam kotak yang besar. Tiga dari kotak-kotak kecil tersebut memiliki gambar tetapi terdapat 1 kotak kecil yang hilang. Kotak yang hilang ini terletak diantara 6 kotak-kotak kecil yang berada pada pilihan jawaban.</p>
                <p>Tugas Anda adalah memilih salah satu dari 6 pilihan jawaban untuk melengkapi bagian yang hilang tersebut.</p>',
                'type' => 'instruction',
            ],
            [
                'section_id' => $cfit->sections[4]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/1/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[4]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/2/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[4]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-3/3/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'F'],
            ],

            // Subtes 3
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 1,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/1/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/2/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/3/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/4/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 5,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/5/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 6,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/6/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 7,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/7/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 8,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/8/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'E'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 9,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/9/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 10,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/10/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 11,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/11/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'F'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 12,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/12/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[5]->id,
                'order' => 13,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/E.webp'],
                    ['key' => 'F', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-3/13/F.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],

            // Contoh Subtes 4
            [
                'section_id' => $cfit->sections[6]->id,
                'order' => 1,
                'text' => '<p>Pada tiap soal terdapat sebuah gambar, pada gambar tersebut memiliki sebuah titik dan sebuah bangun datar.</p>
                <p>Tugas Anda adalah mencari kemungkinan gambar pada tiap pilihan jawaban yang letak titiknya serupa dengan yang dipersoalkan.</p>',
                'type' => 'instruction',
            ],
            [
                'section_id' => $cfit->sections[6]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/1/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[6]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/2/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[6]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/contoh/subtes-4/3/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],

            // Subtes 4
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 1,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/1/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 2,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/2/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 3,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/3/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 4,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/4/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 5,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/5/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 6,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/6/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'B'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 7,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/7/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'C'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 8,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/8/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 9,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/9/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'A'],
            ],
            [
                'section_id' => $cfit->sections[7]->id,
                'order' => 10,
                'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/Soal.webp',
                'type' => 'image_multiple_choice',
                'options' => [
                    ['key' => 'A', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/A.webp'],
                    ['key' => 'B', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/B.webp'],
                    ['key' => 'C', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/C.webp'],
                    ['key' => 'D', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/D.webp'],
                    ['key' => 'E', 'text' => 'assets/landing/images/psikotes-paid/questions/cfit/soal/subtes-4/10/E.webp'],
                ],
                'scoring' => ['correct_answer' => 'D'],
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
