<?php

namespace Database\Seeders\Tools\HEXACO;

use App\Models\Question;
use App\Models\Tool;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HexacoQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hexaco = Tool::with('sections')->firstWhere('name', 'HEXACO');

        $questions = [
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 1,
                'type' => 'likert',
                'text' => 'Saya akan merasa bosan ketika berkunjung ke galeri seni',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "aesthetic appreciation",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 2,
                'type' => 'likert',
                'text' => 'Saya cukup sering membersihkan rumah dan kantor saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "organization",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 3,
                'type' => 'likert',
                'text' => 'Saya jarang menyumpah, meskipun saat menghadapi orang yang sangat menyinggung',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "forgiveness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 4,
                'type' => 'likert',
                'text' => 'Secara umum, saya merasa cukup puas dengan diri saya saat ini',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social self-esteem",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 5,
                'type' => 'likert',
                'text' => 'Saya akan merasa cemas bila harus berpergian dalam keadaan cuaca yang buruk',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "fearfulness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 6,
                'type' => 'likert',
                'text' => 'Jika saya ingin sesuatu dari orang yang saya benci, saya akan bersikap sangat manis untuk mendapatkannya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "sincerity",
                    "reverse_scored" => true,
                ],
            ],

            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 7,
                'type' => 'likert',
                'text' => 'Sejarah dan keadaan politik di negara lain merupakan hal yang menarik bagi saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "insquitiveness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 8,
                'type' => 'likert',
                'text' => 'Saat bekerja, saya sering menetapkan target yang menantang',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "diligence",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 9,
                'type' => 'likert',
                'text' => 'Orang-orang kadang berkata bahwa saya terlalu kritis pada orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "gentleness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 10,
                'type' => 'likert',
                'text' => 'Saya jarang mengungkapkan pendapat dalam suatu rapat atau pertemuan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social boldness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 11,
                'type' => 'likert',
                'text' => 'Terkadang saya terlalu cemas memikirkan hal-hal kecil',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "anxiety",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 12,
                'type' => 'likert',
                'text' => 'Bila saya tahu bahwa saya tidak akan tertangkap, saya akan mencuri uang milyaran rupiah',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "fairness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 13,
                'type' => 'likert',
                'text' => 'Saya lebih menyukai pekerjaan dengan tugas-tugas rutin daripada tugas yang kreatif',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "creativity",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 14,
                'type' => 'likert',
                'text' => 'Saya sering mengecek kembali pekerjaan yang telah dikerjakan untuk meminimalisir kesalahan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "perfectionism",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 15,
                'type' => 'likert',
                'text' => 'Orang-orang kadang berkata bahwa saya terlalu keras kepala',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "flexibility",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 16,
                'type' => 'likert',
                'text' => 'Saya tidak suka berbasa-basi dengan orang-orang',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "sociability",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 17,
                'type' => 'likert',
                'text' => 'Ketika saya mengalami pengalaman yang menyakitkan, saya butuh seseorang agar merasa nyaman',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "dependence",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 18,
                'type' => 'likert',
                'text' => 'Memiliki banyak uang bukanlah suatu hal yang sangat penting bagi saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "greed-avoidance",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 19,
                'type' => 'likert',
                'text' => 'Menurut saya, memperhatikan ide-ide yang radikal hanya membuang-buang waktu',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "unconventionality",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 20,
                'type' => 'likert',
                'text' => 'Keputusan yang saya buat lebih didasarkan pada perasaan saat itu daripada pemikiran yang hati-hati',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "prudence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 21,
                'type' => 'likert',
                'text' => 'Orang-orang berpikir bahwa saya adalah orang yang mudah marah',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "patience",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 22,
                'type' => 'likert',
                'text' => 'Saya merasa energik sepanjang waktu',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "liveliness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 23,
                'type' => 'likert',
                'text' => 'Bila melihat orang lain menangis, saya merasa ingin menangis pula',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "sentimentality",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 24,
                'type' => 'likert',
                'text' => 'Saya adalah orang yang biasa saja dan tidak lebih baik daripada orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "modesty",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 25,
                'type' => 'likert',
                'text' => 'Saya tidak akan menghabiskan waktu untuk membaca buku puisi',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "aesthetic appreciation",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 26,
                'type' => 'likert',
                'text' => 'Saya merencanakan setiap tugas atau kegiatan, agar tidak kewalahan pada menit-menit terakhir',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "organization",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 27,
                'type' => 'likert',
                'text' => 'Prinsip saya pada orang yang berperilaku buruk adalah "memaafkan dan melupakan"',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "forgiveness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 28,
                'type' => 'likert',
                'text' => 'Saya pikir banyang orang menyukasi salah satu sifat saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social self-esteem",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 29,
                'type' => 'likert',
                'text' => 'Saya tidak masalah bila harus melakukan pekerjaan yang berbahaya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "fearfulness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 30,
                'type' => 'likert',
                'text' => 'Saya tidak akan menjilat untuk mendapatkan promosi pekerjaan, walaipun cara itu cukup efektif',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "sincerity",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 31,
                'type' => 'likert',
                'text' => 'Saya senang melihat berbagai tempat dari peta',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "insquitiveness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 32,
                'type' => 'likert',
                'text' => 'Saya sering berusaha sangat keras agar dapat mencapai tujuan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "deligence",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 33,
                'type' => 'likert',
                'text' => 'Secara umum, saya menerima kelemahan orang lain tanpa banyak mengeluh',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "gentleness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 34,
                'type' => 'likert',
                'text' => 'Dalam suatu situasi sosial, biasanya saya adalah orang yang pertama kali bertindak',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social boldness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 35,
                'type' => 'likert',
                'text' => 'Saya lebih santai dibandingkan orang-orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "anxiety",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 36,
                'type' => 'likert',
                'text' => 'Saya akan tergoda untuk mencuri bila dalam keadaan keuangan yang mendesak',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "fairness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 37,
                'type' => 'likert',
                'text' => 'Saya senang membuat karya, seperti novel, lagu, atau lukisan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "creativity",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 38,
                'type' => 'likert',
                'text' => 'Saat mengerjakan suatu hal, saya tidak terlalu fokus pada detailnya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "perfectionism",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 39,
                'type' => 'likert',
                'text' => 'Saya biasanya tidak terlalu mempertahankan pendapat bila orang-orang tidak setuju',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "flexibility",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 40,
                'type' => 'likert',
                'text' => 'Saya senang berada di antara banyak orang yang bisa diajak bicara',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "sociability",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 41,
                'type' => 'likert',
                'text' => 'Saya dapat menangani situasi sulit tanpa adanya dukungan emosional dari orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "dependence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 42,
                'type' => 'likert',
                'text' => 'Saya ingin tinggal di suatu perumahan mewah yang dikelilingi orang-orang kaya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "greed-avoidance",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 43,
                'type' => 'likert',
                'text' => 'Saya senang pada orang yang memiliki pandangan yang tidak konvensional',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "unconventionality",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 44,
                'type' => 'likert',
                'text' => 'Saya banyak melakukan kesalahan karena saya sering bertindak tanpa berpikir',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "prudence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 45,
                'type' => 'likert',
                'text' => 'Saya jarang merasa marah, walaupun pada orang yang memperlakukan saya secara buruk',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "patience",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 46,
                'type' => 'likert',
                'text' => 'Hampir setiap hari saya selalu merasa ceria dan optimis',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "liveliness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 47,
                'type' => 'likert',
                'text' => 'Ketika orang yang saya kenal merasa sedih, saya merasa berempati',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "sentimentality",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 48,
                'type' => 'likert',
                'text' => 'Saya tidak ingin orang-orang memperlakukan saya sebagai orang yang superior',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "modesty",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 49,
                'type' => 'likert',
                'text' => 'Jika saya memiliki kesempatan, saya ingin menghadiri acara konser musik klasik',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "aesthetic appreciation",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 50,
                'type' => 'likert',
                'text' => 'Orang-orang kadang bercanda tentang keadaan kamar atau meja saya yang berantakan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "organization",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 51,
                'type' => 'likert',
                'text' => 'Jika seseorang pernah mengkhianati saya, maka saya akan selalu mencurigainya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "forgiveness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 52,
                'type' => 'likert',
                'text' => 'Saya merasa bahwa saya adalah orang yang kurang populer',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social self-esteem",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 53,
                'type' => 'likert',
                'text' => 'Dalam keadaan bahaya, saya merasa sangat takut',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "fearfulness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 54,
                'type' => 'likert',
                'text' => 'Jika saya mempunyai keperluan pada seseorang, saya akan bersikap sangat manis padanya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "sincerity",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 55,
                'type' => 'likert',
                'text' => 'Saya akan merasa sangat bosan bila membaca buku tentang sejarah ilmu pengetahuan dan teknologi',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "insquitiveness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 56,
                'type' => 'likert',
                'text' => 'Seringkali ketika saya menetapkan target, saya malah tidak bisa meraihnya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "deligence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 57,
                'type' => 'likert',
                'text' => 'Saya mencoba untuk tidak menilai orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "gentleness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 58,
                'type' => 'likert',
                'text' => 'Ketika saya berada di dalam grup, saya sering berbicara untuk mewakili kepentingan yang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social boldness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 59,
                'type' => 'likert',
                'text' => 'Saya jarang, bahkan tidak pernah sulit tidur karena merasa stres atau cemas',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "anxiety",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 60,
                'type' => 'likert',
                'text' => 'Saya tidak akan pernah mau menerima suap walaupun jumlahnya sangat besar',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "fairness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 61,
                'type' => 'likert',
                'text' => 'Orang-orang sering bilang bahwa saya memiliki imajinasi yang baik',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "creativity",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 62,
                'type' => 'likert',
                'text' => 'Saya selalu berusaha untuk teliti dalam bekerja, walaupun dalam kondisi mendesak',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "perfectionism",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 63,
                'type' => 'likert',
                'text' => 'Saat ada orang yang berkata bahwa saya salah, maka reaksi pertama saya adalah mendebatnya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "flexibility",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 64,
                'type' => 'likert',
                'text' => 'Saya lebih menyukai pekerjaan yang menuntut interaaksi sosial daripada bekerja sendiri',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "sociability",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 65,
                'type' => 'likert',
                'text' => 'Kapanpun saya merasa cemas akan sesuatu, saya ingin bercerita pada orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "dependence",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 66,
                'type' => 'likert',
                'text' => 'Saya ingin pamer dengan mengendarai kendaraaan mewah',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "greed-avoidance",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 67,
                'type' => 'likert',
                'text' => 'Menurut saya, saya adalah orang yang eksentrik',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "unconventionality",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 68,
                'type' => 'likert',
                'text' => 'Saya tidak membiarkan diri saya bertindak implusif',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "prudence",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 69,
                'type' => 'likert',
                'text' => 'Sebagian besar orang lebih cepat marah dibandingkan saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "patience",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 70,
                'type' => 'likert',
                'text' => 'Orang-orang sering menasehati agar saya lebih ceria',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "liveliness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 71,
                'type' => 'likert',
                'text' => 'Saya akan merasa sangat sedih saat orang yang dekat dengan saya akan pergi jauh untuk waktu yang lama',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "sentimentality",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 72,
                'type' => 'likert',
                'text' => 'Saya pikir, saya berhak untuk mendapatkan kehormatan yang lebih besar daripada orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "modesty",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 73,
                'type' => 'likert',
                'text' => 'Terkadang saya hanya ingin memandangi angin yang berhembus ke pepohonan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "aesthetic appreciation",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 74,
                'type' => 'likert',
                'text' => 'Ketiak bekerja, saya terkadang merasa kesulitan karena sulit mengorganisir tugas',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "organization",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 75,
                'type' => 'likert',
                'text' => 'Saya merasa sulit untuk memaafkan orang yang telah bertindak kasar kepada saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "forgiveness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 76,
                'type' => 'likert',
                'text' => 'Saya terkadang merasa bahwa saya adalah orang yang kurang berharga',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social self-esteem",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 77,
                'type' => 'likert',
                'text' => 'Walaupund alam keadaan darurat, saya tidak akan merasa panik',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "fearfulness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 78,
                'type' => 'likert',
                'text' => 'Saya akan berpura-pura menyukai seseorang agar mendapatkan abntuan darinya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "sincerity",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 79,
                'type' => 'likert',
                'text' => 'Saya tidak pernah merasa senang membaca ensiklopedia',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "insquitiveness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 80,
                'type' => 'likert',
                'text' => 'Saya hanaya mengerjakan tugas saya sesuai standar',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "deligence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 81,
                'type' => 'likert',
                'text' => 'Walaupun orang melakukan banyak kesalahan, saya jarang berkata hal yang negatif padanya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "gentleness",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 82,
                'type' => 'likert',
                'text' => 'Saya cenderug memeiliki kesadaran diri saat berbicara di dalam kelompok',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "social boldness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 83,
                'type' => 'likert',
                'text' => 'Saya merasa sangat cemas saat menunggu kabar tentang keputusan penting',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "anxiety",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 84,
                'type' => 'likert',
                'text' => 'Saya tergoda untuk menggunakan uang palsu, bila saya yakin saya tidak akan tertangkap',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "fairness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 85,
                'type' => 'likert',
                'text' => 'Saya tidak merasa sebagai orang yang artistik atau kreatif',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "creativity",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 86,
                'type' => 'likert',
                'text' => 'Orang-orang sering bilang bahwa saya adalah orang yang perfeksionis',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "perfectionism",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 87,
                'type' => 'likert',
                'text' => 'Saya merasa sulit berkompromi dengan orang lain, bila saya merasa bahwa sayalah yang benar',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "flexibility",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 88,
                'type' => 'likert',
                'text' => 'Hal pertama yang saya lakukan di tempat baru adalah mencari teman',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "sociability",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 89,
                'type' => 'likert',
                'text' => 'Saya jarang mendiskusikan masalah saya dengan orang lain',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "dependence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 90,
                'type' => 'likert',
                'text' => 'Saya akan merasa sangat puas dan senang bila memiliki barang-barang mawah dan mahal',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "greed-avoidance",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 91,
                'type' => 'likert',
                'text' => 'Berdiskusi tentang filsafat membuat saya bosan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "opennes to experience",
                    "sub_scale" => "unconventionality",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 92,
                'type' => 'likert',
                'text' => 'Saya lebih baik melakukan apa yang ada di dalam pikiran saya daripada terpaku pada satu rencana',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "conscientiousness",
                    "sub_scale" => "prudence",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 93,
                'type' => 'likert',
                'text' => 'Saya merasa sulit untuk bersabar ketika ada orang yang memancing emosi',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "agreeableness",
                    "sub_scale" => "patience",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 94,
                'type' => 'likert',
                'text' => 'Sebagian besar orang lebih ceria dan optimis dibandingkan dengan saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "extraversion",
                    "sub_scale" => "liveliness",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 95,
                'type' => 'likert',
                'text' => 'Saya dapat menahan diri agar tidak emosional walaupun dalam keadaan yang sentimental',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "emotionality",
                    "sub_scale" => "sentimentality",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 96,
                'type' => 'likert',
                'text' => 'Saya ingin orang-orang tahu bahwa saya adalah orang yang penting dan memilih status tinggi',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "honesty-humility",
                    "sub_scale" => "modesty",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 97,
                'type' => 'likert',
                'text' => 'Saya merasa simpati pada orang-orang yang tidak seberuntung saya',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "alturism",
                    "sub_scale" => "alturism",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 98,
                'type' => 'likert',
                'text' => 'Saya berusaha membantu orang yang sedang membutuhkan bantuan',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "alturism",
                    "sub_scale" => "alturism",
                    "reverse_scored" => false,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 99,
                'type' => 'likert',
                'text' => 'Saya tidak akan merasa bersalah menyakiti orang yang tidak saya sukai',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "alturism",
                    "sub_scale" => "alturism",
                    "reverse_scored" => true,
                ],
            ],
            [
                'section_id' => $hexaco->sections[0]->id,
                'order' => 100,
                'type' => 'likert',
                'text' => 'Orang-orang melihat saya sebagai orang yang keras hati',
                'options' => [
                    ['value' => 1, 'text' => 'Sangat Tidak Setuju'],
                    ['value' => 2, 'text' => 'Tidak Setuju'],
                    ['value' => 3, 'text' => 'Netral'],
                    ['value' => 4, 'text' => 'Setuju'],
                    ['value' => 5, 'text' => 'Sangat Setuju'],
                ],
                'scoring' => [
                    "scale" => "alturism",
                    "sub_scale" => "alturism",
                    "reverse_scored" => true,
                ],
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
